export const constSchema = {
  processDate: 'processDate',
  plantCode: 'plantCode',
  plantName: 'plantName',
  vendorCode: 'vendorCode',
  vendorTypeName: 'vendorTypeName',
  vendorName: 'vendorName',
  basketCode: 'basketCode',
  basketName: 'basketName',
  quantity: 'totalQuanty',
  uom: 'uom',
  borrowBasketQuantity: 'borrowBasketQuantity',
  lendBasketQuantity: 'lendBasketQuantity',
  status: 'status',
  netOff: 'netOff',
};
