import { constSchema } from './schema';

export const makeTableColumns = () => [
  {
    headerName: 'Ngày xử lý',
    field: constSchema.processDate,
    resizable: true,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    pinnedRowCellRenderer: 'customPinnedRowRenderer',
    pinnedRowCellRendererParams: { style: { fontWeight: 'bold' } },
    tooltipField: 'processDate',
  },
  {
    headerName: 'Mã ĐV',
    field: constSchema.plantCode,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    resizable: true,
    tooltipField: 'plantCode',
  },
  {
    headerName: 'Đơn vị quản lý',
    field: constSchema.plantName,
    resizable: true,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    tooltipField: 'plantName',
  },
  {
    headerName: 'Loại Vendor',
    field: constSchema.vendorTypeName,
    resizable: true,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    tooltipField: 'vendorTypeName',
  },
  {
    headerName: 'Mã Vendor',
    field: constSchema.vendorCode,
    resizable: true,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    tooltipField: 'vendorCode',
  },
  {
    headerName: 'Vendor',
    field: constSchema.vendorName,
    resizable: true,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    tooltipField: 'vendorName',
  },
  {
    headerName: 'Mã khay sọt',
    field: constSchema.basketCode,
    resizable: true,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    tooltipField: 'basketCode',
  },
  {
    headerName: 'Tên khay sọt',
    field: constSchema.basketName,
    resizable: true,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    tooltipField: 'basketName',
  },
  {
    headerName: 'Đơn vị tính',
    field: constSchema.uom,
    resizable: true,
    headerClass: 'ag-border-left',
    tooltipField: 'uom',
    cellClass: 'ag-border-left',
  },
  {
    headerName: 'Mượn',
    field: constSchema.borrowBasketQuantity,
    cellStyle: {
      textAlign: 'right',
    },
    tooltipField: 'borrowBasketQuantity',

    resizable: true,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    pinnedRowCellRenderer: 'customPinnedRowRenderer',
    pinnedRowCellRendererParams: { style: { fontWeight: 'bold' } },
  },
  {
    headerName: 'Cho mượn',
    field: constSchema.lendBasketQuantity,
    cellStyle: {
      textAlign: 'right',
    },
    tooltipField: 'lendBasketQuantity',
    resizable: true,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    pinnedRowCellRenderer: 'customPinnedRowRenderer',
    pinnedRowCellRendererParams: { style: { fontWeight: 'bold' } },
  },
  {
    headerName: 'Net off',
    field: constSchema.netOff,
    cellStyle: {
      textAlign: 'right',
    },
    tooltipField: 'netOff',
    resizable: true,
    headerClass: 'ag-border-left',
    cellClass: 'ag-border-left',
    pinnedRowCellRenderer: 'customPinnedRowRenderer',
    pinnedRowCellRendererParams: { style: { fontWeight: 'bold' } },
  },
  {
    headerName: 'Trạng thái',
    field: constSchema.status,
    resizable: true,
    cellClass: 'ag-border-left-right',
    headerClass: 'ag-border-left-right',
  },
];
