export const FETCH_ORG_LIST = 'fc40/ConfirmDataLSX/FETCH_ORG_LIST';
export const FETCH_ORG_LIST_SUCCESS =
  'fc40/ConfirmDataLSX/FETCH_ORG_LIST_SUCCESS';
export const FETCH_TABLE_DATA = 'fc40/ConfirmDataLSX/FETCH_TABLE_DATA';
export const FETCH_TABLE_DATA_SUCCESS =
  'fc40/ConfirmDataLSX/FETCH_TABLE_DATA_SUCCESS';
export const SUBMIT_TABLE_DATA = 'fc40/ConfirmDataLSX/SUBMIT_TABLE_DATA';
export const EXPORT_EXCEL = 'fc40/ConfirmDataLSX/EXPORT_EXCEL';
export const SUBMIT_TABLE_DATA_SUCCESS =
  'fc40/ConfirmDataLSX/SUBMIT_TABLE_DATA_SUCCESS';
export const UPDATE_TABLE_DATA = 'fc40/ConfirmDataLSX/UPDATE_TABLE_DATA';
