export const formDataSchema = {
  orgStocktaking: [],
  orgListStocktaking: [],
  DateTo: '',
  DateFrom: '',
  date: '',
  basketCode: [],
  listBasketCode: [],
  status: [],
  statusList: [],
  stocktakingType: [],
  stocktakingTypeList: [],
  afterStocktaking: [],
  afterStocktakingList: [],
  basketStockTakingCode: '',
  stocktakingRound: '',
  isDifference: '',
  ConfigShowDate: 0,
};
