export const demoFormData = {
  exportingOrg: [
    { value: '001', label: 'Đơn vị 1' },
    { value: '002', label: 'Đơn vị 2' },
  ],
  importingOrg: [
    { value: '001', label: 'Đơn vị 1' },
    { value: '002', label: 'Đơn vị 2' },
  ],
  productCode: [
    { value: '001', label: 'Sản phẩm 1' },
    { value: '002', label: 'Sản phẩm 2' },
  ],
  productName: [
    { value: '001', label: 'Sản phẩm 1' },
    { value: '002', label: 'Sản phẩm 2' },
  ],
};

export const demoFormValues = {
  exportingOrg: '001',
  importingOrg: '001',
  pickingDate: new Date(),
  fromStock: 'Kho Chia Chọn - 3001',
  productCode: '001',
  productName: '001',
};

export const demoTableData = [
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bầu sao ĐR/NL VE',
    plantCode: '2014',
    plantName: 'Farm Lac Duong',
    uom: 'KG',
    actualPickingQuantity: '55',
    exportedQuantity: '25',
    remainQuantity: '25',
    pickingQuantity: '200',
  },
];
