export const FETCH_FORM_DATA = 'app/BCTTTLHKS/FETCH_FORM_DATA';
export const FETCH_FORM_DATA_SUCCESS = 'app/BCTTTLHKS/FETCH_FORM_DATA_SUCCESS';
export const FETCH_REPORT_DATA = 'app/BCTTTLHKS/FETCH_REPORT_DATA';
export const FETCH_REPORT_DATA_SUCCESS =
  'app/BCTTTLHKS/FETCH_REPORT_DATA_SUCCESS';
export const FETCH_MAIN_TABLE_REPORT_DATA =
  'app/BCTTTLHKS/FETCH_MAIN_TABLE_REPORT_DATA';
export const FETCH_MAIN_TABLE_REPORT_DATA_SUCCESS =
  'app/BCTTTLHKS/FETCH_MAIN_TABLE_REPORT_DATA_SUCCESS';
export const CHANGE_SELECTION = 'app/BCTTTLHKS/CHANGE_SELECTION';
export const PRINT_REPORT = 'app/BCTTTLHKS/PRINT_REPORT';
export const EXPORT_REPORT = 'app/BCTTTLHKS/EXPORT_REPORT';
export const ORDER_CHANGE = 'app/BCTTTLHKS/ORDER_CHANGE';
export const SYNC_DATA = 'app/BCTTTLHKS/SYNC_DATA';
export const SYNC_DATA_SUCCESS = 'app/BCTTTLHKS/SYNC_DATA_SUCCESS';

export const SIGNALIR_PROCESSING = 'app/BCTTTLHKS/SIGNALIR_PROCESSING';
