const BASE_URL = 'app/Baskets/BK_BCCTGDXN/ListPage/';
export const SUBMIT_FORM = `${BASE_URL}SUBMIT_FORM`;
export const SUBMIT_FORM_SUCCESS = `${BASE_URL}SUBMIT_FORM_SUCCESS`;
export const FETCH_FORM_DATA = `${BASE_URL}FETCH_FORM_DATA`;
export const FETCH_FORM_DATA_SUCCESS = `${BASE_URL}FETCH_FORM_DATA_SUCCESS`;
export const GET_FORM_DATA_SUCCESS = `${BASE_URL}GET_FORM_DATA_SUCCESS`;
export const PRINT_SELECTED = `${BASE_URL}PRINT_SELECTED`;
export const EXPORT_EXCEL = `${BASE_URL}EXPORT_EXCEL`;
