export const demoTableData = [
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '1560',
    storeName: 'Vinmart Di An',
    route: 'BD-01',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
  {
    storeCode: '3855',
    storeName: 'VM+ BDG 453 Lý Thường Kiệt',
    route: 'BD-02',
    basketName1: null,
    quantity1: null,
    basketName2: null,
    quantity2: null,
    basketName3: null,
    quantity3: null,
  },
];
