export const demoMenuTopData = [
  {
    id: 1,
    label: 'Sản xuất',
    link: '',
    parentId: null,
    children: [
      {
        id: 3,
        label: 'Tạo mới BBGH',
        link: '/tao-moi-bien-ban-giao-hang',
        parentId: 1,
        children: [
          {
            id: 3,
            label: 'DS Điều chỉnh Chia chọn thực tế fasdf asdf asdfsa ',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
          {
            id: 3,
            label: 'Demo Link',
            link: '/chia-hang-cho-vm-vmp',
            parentId: 3,
          },
        ],
      },
      {
        id: 4,
        label: 'Danh sách BBGH',
        link: '/danh-sach-bien-ban-giao-hang',
        parentId: 1,
        children: [],
      },
      {
        id: 5,
        label: 'DS Phiếu nhập kho',
        link: '/danh-sach-phieu-can-nhap-kho',
        parentId: 1,
        children: [],
      },
      {
        id: 9,
        label: 'Danh sách cân tổng',
        link: '/danh-sach-can-hang',
        parentId: 1,
        children: [],
      },
      {
        id: 10,
        label: 'Xác nhận lệnh sản xuất',
        link: '/xac-nhan-du-lieu-tao-lenh-san-xuat',
        parentId: 1,
        children: [],
      },
      {
        id: 12,
        label: 'Cân nhập kho',
        link: '/can-san-pham-nhap-kho',
        parentId: 1,
        children: [],
      },
      // {
      //   id: 33,
      //   label: 'DS Phiếu xuất kho',
      //   link: '/danh-sach-phieu-xuat-kho',
      //   parentId: 1,
      //   children: [],
      // },
      // {
      //   id: 34,
      //   label: 'Tạo phiếu xuất kho',
      //   link: '/tao-phieu-xuat-kho',
      //   parentId: 1,
      //   children: [],
      // },
      // {
      //   id: 36,
      //   label: 'DS Phiếu xuất kho đang cân',
      //   link: '/danh-sach-phieu-dang-can-xuat-kho',
      //   parentId: 1,
      //   children: [],
      // },
      // {
      //   id: 37,
      //   label: 'DS Điều chỉnh Cân NK',
      //   link: '/danh-sach-du-lieu-dieu-chinh',
      //   parentId: 1,
      //   children: [],
      // },
      // {
      //   id: 45,
      //   label: 'DS Phiếu yêu cầu hủy',
      //   link: '/danh-sach-phieu-yeu-cau-huy',
      //   parentId: 1,
      //   children: [],
      // },
      // {
      //   id: 62,
      //   label: 'DS Điều chỉnh Chia chọn thực tế',
      //   link: '/danh-sach-du-lieu-dieu-chinh-chia-chon-thuc-te',
      //   parentId: 1,
      //   children: [],
      // },
      // {
      //   id: 63,
      //   label: 'Danh sách BBGNHH',
      //   link: '/danh-sach-bien-ban-giao-nhan-hang-hoa',
      //   parentId: 1,
      //   children: [],
      // },
      // {
      //   id: 64,
      //   label: 'Tạo mới BBGNHH',
      //   link:
      //     '/danh-sach-bien-ban-giao-nhan-hang-hoa/tao-moi-bien-ban-giao-nhan-hang-hoa',
      //   parentId: 1,
      //   children: [],
      // },
      // {
      //   id: 66,
      //   label: 'Đăng ký khay sọt sau chia chọn',
      //   link: '/dang-ky-thong-tin-khay-sot',
      //   parentId: 1,
      //   children: [],
      // },
    ],
  },
  {
    id: 20,
    label: 'Điều phối',
    link: '',
    parentId: null,
    children: [
      {
        id: 21,
        label: 'DS Cân tổng điều phối',
        link: '/danh-sach-can-tong-dieu-phoi',
        parentId: 20,
        children: [],
      },
      {
        id: 46,
        label: 'Import chia chọn dự kiến',
        link: '/import-file-chia-chon-du-kien',
        parentId: 20,
        children: [],
      },
      {
        id: 49,
        label: 'DS File import chia chọn dự kiến',
        link: '/danh-sach-file-import',
        parentId: 20,
        children: [],
      },
      {
        id: 67,
        label: 'Import giá đã duyệt',
        link: '/import-gia-da-phe-duyet',
        parentId: 20,
        children: [],
      },
    ],
  },
  {
    id: 59,
    label: 'MasterData',
    link: 'NULL',
    parentId: null,
    children: [
      {
        id: 60,
        label: 'Danh sách NCC',
        link: '/danh-sach-nha-cung-cap',
        parentId: 59,
        children: [],
      },
      {
        id: 61,
        label: 'Tạo mới NCC',
        link: '/danh-sach-nha-cung-cap/tao-moi-nha-cung-cap',
        parentId: 59,
        children: [],
      },
    ],
  },
];
