export const FETCH_FIELDS_DATA = 'app/PXKDeliBasket/FETCH_FIELDS_DATA';
export const FETCH_FIELDS_DATA_SUCCESS =
  'app/PXKDeliBasket/FETCH_FIELDS_DATA_SUCCESS';
export const FETCH_TABLE_DATA = 'app/PXKDeliBasket/FETCH_TABLE_DATA';
export const FETCH_TABLE_DATA_SUCCESS =
  'app/PXKDeliBasket/FETCH_TABLE_DATA_SUCCESS';
export const FETCH_ROUTE_AUTOCOMPLETE =
  'app/PXKDeliBasket/FETCH_ROUTE_AUTOCOMPLETE';
export const FETCH_BASKET_AUTOCOMPLETE =
  'app/PXKDeliBasket/FETCH_BASKET_AUTOCOMPLETE';
export const FETCH_CUSTOMER_AUTOCOMPLETE =
  'app/PXKDeliBasket/FETCH_CUSTOMER_AUTOCOMPLETE';
export const SUBMIT_DATA = 'app/PXKDeliBasket/SUBMIT_DATA';
export const PRINT_DATA = 'app/PXKDeliBasket/PRINT_DATA';
export const UPDATE_TABLE_DATA = 'app/PXKDeliBasket/UPDATE_TABLE_DATA';
