export const UPDATE_TABLE_DATA = 'fc40/BBGNHHListPage/UPDATE_TABLE_DATA';
export const SUBMIT_FORM = 'app/BBGNHHListPage/SUBMIT_FORM';
export const SUBMIT_FORM_SUCCESS = 'app/BBGNHHListPage/SUBMIT_FORM_SUCCESS';

export const DELETE_RECORD = 'app/BBGNHHListPage/DELETE_RECORD';
export const DELETE_RECORD_SUCCESS = 'app/BBGNHHListPage/DELETE_RECORD_SUCCESS';
export const EXPORT_EXCEL = 'app/BBGNHHListPage/EXPORT_EXCEL';
export const EXPORT_EXCEL_LOG = 'app/BBGNHHListPage/EXPORT_EXCEL_LOG';
export const EXPORT_EXCEL_ICD = 'app/BBGNHHListPage/EXPORT_EXCEL_ICD';
export const FETCH_FORM_DATA = 'app/BBGNHHListPage/FETCH_FORM_DATA';
export const FETCH_FORM_DATA_SUCCESS =
  'app/BBGNHHListPage/FETCH_FORM_DATA_SUCCESS';
export const PRINT_SELECTED = 'app/BBGNHHListPage/PRINT_SELECTED';
export const CHANGE_SELECTION = 'app/BBGNHHListPage/CHANGE_SELECTION';
export const FETCH_CUSTOMER = 'app/BBGNHHListPage/FETCH_CUSTOMER';
export const FETCH_CREACTOR = 'app/BBGNHHListPage/FETCH_CREACTOR';
