export const demoTableData = [
  {
    id: 1,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 200,
    differentQuantity: 200,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 2,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 200,
    differentQuantity: 200,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 3,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 200,
    differentQuantity: 200,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 1,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 100,
    differentQuantity: 220,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 4,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 200,
    differentQuantity: 200,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 3,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 200,
    differentQuantity: 200,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 1,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 100,
    differentQuantity: 220,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 4,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 200,
    differentQuantity: 200,
    differentRatio: 23,
    differentRatioString: '23%',
  },

  {
    id: 3,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 200,
    differentQuantity: 200,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 1,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 100,
    differentQuantity: 220,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 4,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 200,
    differentQuantity: 200,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 3,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 200,
    differentQuantity: 200,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 1,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 100,
    differentQuantity: 220,
    differentRatio: 23,
    differentRatioString: '23%',
  },
  {
    id: 4,
    processDate: '04/07/2019',
    processorName: 'Nguyễn Văn A',
    processorCode: 'NVA',
    farmSupplierName: 'Farm số 1',
    farmSupplierCode: 'FF001',
    planningCode: 'KH002',
    productName: 'Sản Phẩm X',
    customerCode: 'CUST_A102',
    customerName: 'Nguyễn Văn B',
    saleUnit: 'KG',
    planedPickingQuantity: 420,
    realQuantity: 200,
    differentQuantity: 200,
    differentRatio: 23,
    differentRatioString: '23%',
  },
];
// export const totalData
