const BASE_URL = 'app/Baskets/HistoryPhysicalInventoryReport/ListPage/';
export const SUBMIT_FORM = `${BASE_URL}SUBMIT_FORM`;
export const SUBMIT_FORM_SUCCESS = `${BASE_URL}SUBMIT_FORM_SUCCESS`;
export const FETCH_FORM_DATA = `${BASE_URL}FETCH_FORM_DATA`;
export const FETCH_FORM_DATA_SUCCESS = `${BASE_URL}FETCH_FORM_DATA_SUCCESS`;
export const GET_FORM_DATA_SUCCESS = `${BASE_URL}GET_FORM_DATA_SUCCESS`;
export const CHANGE_ORDER = `${BASE_URL}CHANGE_ORDER`;
export const PROCEED_REPORT = `${BASE_URL}PROCEED_REPORT`;
