export const sanPhamAuto = [
  {
    productCode: '2005',
    productDescription: 'TP-Cà chua',
  },
  {
    productCode: '2004',
    productDescription: 'TP-Cà chua 1',
  },
  {
    productCode: '2003',
    productDescription: 'TP-Cà chua 2',
  },
  {
    productCode: '2002',
    productDescription: 'TP-Cà chua 3',
  },
  {
    productCode: '2001',
    productDescription: 'TP-Cà chua 4',
  },
  {
    productCode: '2000',
    productDescription: 'TP-Cà chua 5',
  },
];

export const danhSachDuLieuDieuChinh = [
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bau sao L1 VE',
    receiverCode: '2000445',
    receiverName: 'HTX Hiền Thi',
    uom: 'KG',
    deliveryQuantity: 200,
    pickingQuantity: 250,
    differentQuantity: 50,
    differentRatioString: '25%',
    isModify: true,
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bau sao L1 VE',
    receiverCode: '2000219',
    receiverName: 'HTX Hiền Thi',
    uom: 'KG',
    deliveryQuantity: 100,
    pickingQuantity: 120,
    differentQuantity: 20,
    differentRatioString: '20%',
    isModify: true,
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bau sao L1 VE',
    receiverCode: '2000219',
    receiverName: 'HTX Phước An',
    uom: 'KG',
    deliveryQuantity: 500,
    pickingQuantity: 450,
    differentQuantity: -50,
    differentRatioString: '-10%',
    isModify: true,
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bau sao L1 VE',
    receiverCode: '2014',
    receiverName: 'Farm Lạc Dương',
    uom: 'KG',
    deliveryQuantity: 100,
    pickingQuantity: 120,
    differentQuantity: 20,
    differentRatioString: '20%',
    isModify: true,
  },
  {
    planningCode: '91000096',
    productCode: '51000096',
    productName: 'TP-Bau sao L1 VE',
    receiverCode: '2000215',
    receiverName: 'HTX Quyết Chiến',
    uom: 'KG',
    deliveryQuantity: 520,
    pickingQuantity: 500,
    differentQuantity: -20,
    differentRatioString: '-4%',
    isModify: false,
  },
  {
    planningCode: '91000118',
    productCode: '51000118',
    productName: 'TP-Ca chua DL L1 VE',
    receiverCode: '2014',
    receiverName: 'Farm Lạc Dương',
    uom: 'KG',
    deliveryQuantity: 313,
    pickingQuantity: 310,
    differentQuantity: -3,
    differentRatioString: '-1%',
    isModify: false,
  },
];
