export const demoFormData = {
  org: [
    {
      value: '4002',
      label: 'Sài Đồng',
    },
    {
      value: '02',
      label: 'Đơn vị 2',
    },
    {
      value: '03',
      label: 'Đơn vị 3',
    },
  ],
  uom: [
    {
      value: 'kg',
      label: 'KG',
    },
    {
      value: 'cai',
      label: 'Cái',
    },
  ],
  productionRegion: [
    {
      value: '01',
      label: 'Miền Bắc',
    },
    {
      value: '02',
      label: 'Lâm Đồng',
    },
    {
      value: '03',
      label: 'Miền Nam',
    },
  ],
  farmNCC: [
    {
      value: 0,
      label: 'Tất cả',
    },
    {
      value: '2000',
      label: 'Farm 1',
    },
    {
      value: '2001',
      label: 'Farm 2',
    },
    {
      value: '2002',
      label: 'Farm 3',
    },
  ],
  productCat: [
    {
      value: 0,
      label: 'Tất cả',
    },
    {
      value: '001',
      label: 'Rau ăn quả',
    },
    {
      value: '002',
      label: 'Rau ăn lá',
    },
  ],
  productSource: [
    {
      value: '001',
      label: 'Nguồn 1',
    },
    {
      value: '002',
      label: 'Nguồn 2',
    },
    {
      value: '003',
      label: 'Nguồn 3',
    },
  ],
};

export const demoTableData = [
  {
    productionRegion: 'Miền Bắc',
    planningCode: '90000319',
    productSource: 'TM',
    productionDate: '15/06/2019',
    plantName: 'NSC Sài Đồng',
    farmNCC: 'Farm Tam Đảo',
    productCat: 'Rau ăn quả',
    productCode: '42002024',
    productName: 'BTP-Đậu bắp DL L1 MT',
    batch: '2001190615',
    uom: 'KG',

    /* Tồn đầu kỳ */
    tdkBTP: 10,
    tdkLoai1: null,
    tdkLoai2: null,

    /* Nhập mới trong ngày */
    nmtnBTP: 100,
    nmtnBTPKTC: null, // BTP không tham chiếu
    nmtnLoai1: null,
    nmtnLoai2: null,

    /* Kết quả sơ chế */
    kqscXuatBTP: 100,
    kqscLoai1: null,
    kqscLoai2: null,
    kqscPhePham: null,
    kqscTongLoai1: null,

    /* Kết quả xuất hàng */
    kqxhBTP: null,
    kqxhLoai1: null,
    kqxhLoai2: null,

    /* Hàng hủy */
    hhBTP: null,
    hhLoai1: null,
    hhLoai2: null,

    /* Tồn kho */
    tkBTP: null,
    tkLoai1: null,
    tkLoai2: null,

    /* Tỉ lệ thu hồi */
    tlthDinhMuc: null,
    tlthThucTe: null,
  },
  {
    productionRegion: 'Miền Bắc',
    planningCode: '90000319',
    productSource: 'TM',
    productionDate: '15/06/2019',
    plantName: 'NSC Sài Đồng',
    farmNCC: 'Farm Tam Đảo',
    productCat: 'Rau ăn quả',
    productCode: '42002024',
    productName: 'BTP-Đậu bắp DL L1 MT',
    batch: '2001190615',
    uom: 'KG',

    /* Tồn đầu kỳ */
    tdkBTP: 10,
    tdkLoai1: null,
    tdkLoai2: null,

    /* Nhập mới trong ngày */
    nmtnBTP: 100,
    nmtnBTPKTC: null, // BTP không tham chiếu
    nmtnLoai1: null,
    nmtnLoai2: null,

    /* Kết quả sơ chế */
    kqscXuatBTP: 100,
    kqscLoai1: null,
    kqscLoai2: null,
    kqscPhePham: null,
    kqscTongLoai1: null,

    /* Kết quả xuất hàng */
    kqxhBTP: null,
    kqxhLoai1: null,
    kqxhLoai2: null,

    /* Hàng hủy */
    hhBTP: null,
    hhLoai1: null,
    hhLoai2: null,

    /* Tồn kho */
    tkBTP: null,
    tkLoai1: null,
    tkLoai2: null,

    /* Tỉ lệ thu hồi */
    tlthDinhMuc: null,
    tlthThucTe: null,
  },
];

export const demoTableResponse = {
  statusCode: 200,
  message: '',
  developerMessage: '',
  data: {
    openingStockSemiProductTotal: 789.66,
    openingStockProductType1Total: 0,
    openingStockProductType2Total: 0,
    importSemiProductTotal: 0,
    importSemiProductNoRefTotal: 0,
    importProductType1Total: 0,
    importProductType2Total: 0,
    exportSemiProductProcessingTotal: 0,
    importProductType1ProcessingTotal: 0,
    importProductType2ProcessingTotal: 0,
    wasteQuantityTotal: 0,
    productType1Total: 0,
    exportSemiProductTotal: 0,
    exportProductType1Total: 0,
    exportProductType2Total: 0,
    exportCancelationSemiProductTotal: 0,
    exportCancelationProductType1Total: 0,
    exportCancelationProductType2Total: 0,
    closingStockSemiProductTotal: 789.66,
    closingStockProductType1Total: 0,
    closingStockProductType2Total: 0,
    inventoryReportDetails: [
      {
        region: null,
        planningCode: '90000005',
        source: 'SX',
        dateProcess: '2019-10-03T00:00:00',
        plantCode: '2001',
        plantName: 'Farm Tam Đảo',
        farmSupplierCode: '2001',
        farmSupplierName: 'Farm Tam Đảo',
        materialGroup: '5011',
        productCode: '51000014',
        productName: 'TP-Cải chíp L1 VE',
        batch: '2001190930',
        uom: 'KG',
        openingStockSemiProduct: null,
        openingStockProductType1: 0,
        openingStockProductType2: null,
        importSemiProduct: null,
        importSemiProductNoRef: null,
        importProductType1: 0,
        importProductType2: null,
        exportSemiProductProcessing: null,
        importProductType1Processing: 0,
        importProductType2Processing: null,
        wasteQuantity: null,
        productType1: 0,
        exportSemiProduct: null,
        exportProductType1: 0,
        exportProductType2: null,
        exportCancelationSemiProduct: null,
        exportCancelationProductType1: 0,
        exportCancelationProductType2: null,
        closingStockSemiProduct: null,
        closingStockProductType1: 0,
        closingStockProductType2: null,
        planReceiveRatio: null,
        realReceiveRatio: null,
      },
      {
        region: null,
        planningCode: null,
        source: null,
        dateProcess: null,
        plantCode: null,
        plantName: null,
        farmSupplierCode: null,
        farmSupplierName: null,
        materialGroup: null,
        productCode: null,
        productName: null,
        batch: null,
        uom: null,
        openingStockSemiProduct: null,
        openingStockProductType1: null,
        openingStockProductType2: null,
        importSemiProduct: null,
        importSemiProductNoRef: null,
        importProductType1: null,
        importProductType2: null,
        exportSemiProductProcessing: null,
        importProductType1Processing: null,
        importProductType2Processing: null,
        wasteQuantity: null,
        productType1: null,
        exportSemiProduct: null,
        exportProductType1: null,
        exportProductType2: null,
        exportCancelationSemiProduct: null,
        exportCancelationProductType1: null,
        exportCancelationProductType2: null,
        closingStockSemiProduct: null,
        closingStockProductType1: null,
        closingStockProductType2: null,
        planReceiveRatio: null,
        realReceiveRatio: null,
      },
      {
        region: null,
        planningCode: null,
        source: null,
        dateProcess: null,
        plantCode: null,
        plantName: null,
        farmSupplierCode: null,
        farmSupplierName: null,
        materialGroup: null,
        productCode: null,
        productName: null,
        batch: null,
        uom: null,
        openingStockSemiProduct: null,
        openingStockProductType1: null,
        openingStockProductType2: null,
        importSemiProduct: null,
        importSemiProductNoRef: null,
        importProductType1: null,
        importProductType2: null,
        exportSemiProductProcessing: null,
        importProductType1Processing: null,
        importProductType2Processing: null,
        wasteQuantity: null,
        productType1: null,
        exportSemiProduct: null,
        exportProductType1: null,
        exportProductType2: null,
        exportCancelationSemiProduct: null,
        exportCancelationProductType1: null,
        exportCancelationProductType2: null,
        closingStockSemiProduct: null,
        closingStockProductType1: null,
        closingStockProductType2: null,
        planReceiveRatio: null,
        realReceiveRatio: null,
      },
      {
        region: null,
        planningCode: '90000010',
        source: 'SX',
        dateProcess: '2019-10-03T00:00:00',
        plantCode: '2001',
        plantName: 'Farm Tam Đảo',
        farmSupplierCode: '2001',
        farmSupplierName: 'Farm Tam Đảo',
        materialGroup: '5011',
        productCode: '41001103',
        productName: 'BTP-Cải ngọt NM DAT VE',
        batch: '2001190720',
        uom: 'KG',
        openingStockSemiProduct: 519.66,
        openingStockProductType1: null,
        openingStockProductType2: null,
        importSemiProduct: 0,
        importSemiProductNoRef: 0,
        importProductType1: null,
        importProductType2: null,
        exportSemiProductProcessing: 0,
        importProductType1Processing: null,
        importProductType2Processing: null,
        wasteQuantity: 0,
        productType1: null,
        exportSemiProduct: 0,
        exportProductType1: null,
        exportProductType2: null,
        exportCancelationSemiProduct: 0,
        exportCancelationProductType1: null,
        exportCancelationProductType2: null,
        closingStockSemiProduct: 519.66,
        closingStockProductType1: null,
        closingStockProductType2: null,
        planReceiveRatio: '0%',
        realReceiveRatio: '0%',
      },
      {
        region: null,
        planningCode: '90000010',
        source: 'SX',
        dateProcess: '2019-10-03T00:00:00',
        plantCode: '2001',
        plantName: 'Farm Tam Đảo',
        farmSupplierCode: '2001',
        farmSupplierName: 'Farm Tam Đảo',
        materialGroup: '5011',
        productCode: '41001103',
        productName: 'BTP-Cải ngọt NM DAT VE',
        batch: '2001190729',
        uom: 'KG',
        openingStockSemiProduct: 270,
        openingStockProductType1: null,
        openingStockProductType2: null,
        importSemiProduct: 0,
        importSemiProductNoRef: 0,
        importProductType1: null,
        importProductType2: null,
        exportSemiProductProcessing: 0,
        importProductType1Processing: null,
        importProductType2Processing: null,
        wasteQuantity: 0,
        productType1: null,
        exportSemiProduct: 0,
        exportProductType1: null,
        exportProductType2: null,
        exportCancelationSemiProduct: 0,
        exportCancelationProductType1: null,
        exportCancelationProductType2: null,
        closingStockSemiProduct: 270,
        closingStockProductType1: null,
        closingStockProductType2: null,
        planReceiveRatio: '0%',
        realReceiveRatio: '0%',
      },
      {
        region: null,
        planningCode: '90000010',
        source: 'SX',
        dateProcess: '2019-10-03T00:00:00',
        plantCode: '2001',
        plantName: 'Farm Tam Đảo',
        farmSupplierCode: '2001',
        farmSupplierName: 'Farm Tam Đảo',
        materialGroup: '5011',
        productCode: '41000051',
        productName: 'BTP-Cải ngọt ĐR/NL VE',
        batch: '2001190826',
        uom: 'KG',
        openingStockSemiProduct: 0,
        openingStockProductType1: null,
        openingStockProductType2: null,
        importSemiProduct: 0,
        importSemiProductNoRef: 0,
        importProductType1: null,
        importProductType2: null,
        exportSemiProductProcessing: 0,
        importProductType1Processing: null,
        importProductType2Processing: null,
        wasteQuantity: 0,
        productType1: null,
        exportSemiProduct: 0,
        exportProductType1: null,
        exportProductType2: null,
        exportCancelationSemiProduct: 0,
        exportCancelationProductType1: null,
        exportCancelationProductType2: null,
        closingStockSemiProduct: 0,
        closingStockProductType1: null,
        closingStockProductType2: null,
        planReceiveRatio: '0%',
        realReceiveRatio: '0%',
      },
      {
        region: null,
        planningCode: '90000010',
        source: 'SX',
        dateProcess: '2019-10-03T00:00:00',
        plantCode: '2001',
        plantName: 'Farm Tam Đảo',
        farmSupplierCode: '2001',
        farmSupplierName: 'Farm Tam Đảo',
        materialGroup: '5011',
        productCode: '41000052',
        productName: 'BTP-Cải ngọt NM/NK GT VE',
        batch: '2001190826',
        uom: 'KG',
        openingStockSemiProduct: 0,
        openingStockProductType1: null,
        openingStockProductType2: null,
        importSemiProduct: 0,
        importSemiProductNoRef: 0,
        importProductType1: null,
        importProductType2: null,
        exportSemiProductProcessing: 0,
        importProductType1Processing: null,
        importProductType2Processing: null,
        wasteQuantity: 0,
        productType1: null,
        exportSemiProduct: 0,
        exportProductType1: null,
        exportProductType2: null,
        exportCancelationSemiProduct: 0,
        exportCancelationProductType1: null,
        exportCancelationProductType2: null,
        closingStockSemiProduct: 0,
        closingStockProductType1: null,
        closingStockProductType2: null,
        planReceiveRatio: '0%',
        realReceiveRatio: '0%',
      },
      {
        region: null,
        planningCode: '90000010',
        source: 'SX',
        dateProcess: '2019-10-03T00:00:00',
        plantCode: '2001',
        plantName: 'Farm Tam Đảo',
        farmSupplierCode: '2001',
        farmSupplierName: 'Farm Tam Đảo',
        materialGroup: '5011',
        productCode: '41000051',
        productName: 'BTP-Cải ngọt ĐR/NL VE',
        batch: '2001190827',
        uom: 'KG',
        openingStockSemiProduct: 0,
        openingStockProductType1: null,
        openingStockProductType2: null,
        importSemiProduct: 0,
        importSemiProductNoRef: 0,
        importProductType1: null,
        importProductType2: null,
        exportSemiProductProcessing: 0,
        importProductType1Processing: null,
        importProductType2Processing: null,
        wasteQuantity: 0,
        productType1: null,
        exportSemiProduct: 0,
        exportProductType1: null,
        exportProductType2: null,
        exportCancelationSemiProduct: 0,
        exportCancelationProductType1: null,
        exportCancelationProductType2: null,
        closingStockSemiProduct: 0,
        closingStockProductType1: null,
        closingStockProductType2: null,
        planReceiveRatio: '0%',
        realReceiveRatio: '0%',
      },
    ],
  },
  meta: {
    pageIndex: 0,
    pageSize: 10,
    count: 181,
    menu: null,
    accessToken: null,
    fullName: null,
    fileName: null,
  },
};
