export const UPDATE_TABLE_DATA = 'fc40/BCDUSLDHListPage/UPDATE_TABLE_DATA';
export const SUBMIT_FORM = 'app/BCDUSLDHListPage/SUBMIT_FORM';
export const SUBMIT_FORM_SUCCESS = 'app/BCDUSLDHListPage/SUBMIT_FORM_SUCCESS';

export const DELETE_RECORD = 'app/BCDUSLDHListPage/DELETE_RECORD';
export const DELETE_RECORD_SUCCESS =
  'app/BCDUSLDHListPage/DELETE_RECORD_SUCCESS';
export const EXPORT_EXCEL = 'app/BCDUSLDHListPage/EXPORT_EXCEL';
export const FETCH_FORM_DATA = 'app/BCDUSLDHListPage/FETCH_FORM_DATA';
export const FETCH_FORM_DATA_SUCCESS =
  'app/BCDUSLDHListPage/FETCH_FORM_DATA_SUCCESS';
export const CHANGE_SELECTION = 'app/BCDUSLDHListPage/CHANGE_SELECTION';
export const FETCH_DELIVER = 'app/BCDUSLDHListPage/FETCH_DELIVER';
export const FETCH_PRODUCT = 'app/BCDUSLDHListPage/FETCH_PRODUCT';
