export const FETCH_FORM_DATA = 'fc40/PXK_VinmartDist/FETCH_FORM_DATA';
export const FETCH_FORM_DATA_SUCCESS =
  'fc40/PXK_VinmartDist/FETCH_FORM_DATA_SUCCESS';
export const FETCH_TABLE_DATA = 'fc40/PXK_VinmartDist/FETCH_TABLE_DATA';
export const FETCH_TABLE_DATA_SUCCESS =
  'fc40/PXK_VinmartDist/FETCH_TABLE_DATA_SUCCESS';
export const UPDATE_TABLE_DATA = 'fc40/PXK_VinmartDist/UPDATE_TABLE_DATA';
export const FETCH_CUSTOMER_AUTOCOMPLETE =
  'fc40/PXK_VinmartDist/FETCH_CUSTOMER_AUTOCOMPLETE';
export const FETCH_SOLDTO_VINMART_AUTOCOMPLETE =
  'fc40/PXK_VinmartDist/FETCH_SOLDTO_VINMART_AUTOCOMPLETE';
export const SUBMIT_CREATE_EXPORT_RECEIPT =
  'fc40/PXK_VinmartDist/SUBMIT_CREATE_EXPORT_RECEIPT';
export const FETCH_PRODUCT = 'fc40/PXK_VinmartDist/FETCH_PRODUCT';
export const FETCH_PLANNING = 'fc40/PXK_VinmartDist/FETCH_PLANNING';
export const FETCH_FARM_NCC = 'fc40/PXK_VinmartDist/FETCH_FARM_NCC';
export const EXPORT_EXCEL = 'fc40/PXK_VinmartDist/EXPORT_EXCEL';
