export const demoTableData = [
  {
    shop: 'Shop 01',
    address: 'Số 2 - Đường 1',
    road: 'Tuyến số 1',
    total: '50',
  },
  {
    shop: 'Shop 02',
    address: 'Số 1 - Đường 1',
    road: 'Tuyến số 1',
    total: '100',
  },
  {
    shop: 'Shop 03',
    address: 'Số 2 - Đường 3',
    road: 'Tuyến số 2',
    total: '200',
  },
  {
    shop: 'Shop 04',
    address: 'Số 4 - Đường 1',
    road: 'Tuyến số 1',
    total: '90',
  },
  {
    shop: 'Shop 05',
    address: 'Số 1 - Đường 5',
    road: 'Tuyến số 4',
    total: '100',
  },
];
export const storeList = [
  {
    basketCode1: null,
    basketCode2: null,
    basketCode3: null,
    basketName1: null,
    basketName2: null,
    basketName3: null,
    deliverQuantity1: null,
    deliverQuantity2: null,
    deliverQuantity3: null,
    quantity: 1.91233,
    routeAddress: 'VM+ HNI Almaz',
    routeCode: 'BD-03',
    shipToCode: '2016',
    soldToCode: '2018',
  },
  {
    basketCode1: null,
    basketCode2: null,
    basketCode3: null,
    basketName1: null,
    basketName2: null,
    basketName3: null,
    deliverQuantity1: null,
    deliverQuantity2: null,
    deliverQuantity3: null,
    quantity: 1.9233,
    routeAddress: 'VM+ HNI Almaz',
    routeCode: 'BD-03',
    shipToCode: '2016',
    soldToCode: '2013',
  },
  {
    basketCode1: null,
    basketCode2: null,
    basketCode3: null,
    basketName1: null,
    basketName2: null,
    basketName3: null,
    deliverQuantity1: null,
    deliverQuantity2: null,
    deliverQuantity3: null,
    quantity: 112.93,
    routeAddress: 'VM+ HNI Almaz',
    routeCode: 'BD-03',
    shipToCode: '2011',
    soldToCode: '2016',
  },
  {
    basketCode1: null,
    basketCode2: null,
    basketCode3: null,
    basketName1: null,
    basketName2: null,
    basketName3: null,
    deliverQuantity1: null,
    deliverQuantity2: null,
    deliverQuantity3: null,
    quantity: 132.93,
    routeAddress: 'VM+ HNI Almaz',
    routeCode: 'BD-03',
    shipToCode: '2014',
    soldToCode: '2016',
  },
  {
    basketCode1: null,
    basketCode2: null,
    basketCode3: null,
    basketName1: null,
    basketName2: null,
    basketName3: null,
    deliverQuantity1: null,
    deliverQuantity2: null,
    deliverQuantity3: null,
    quantity: 1.93,
    routeAddress: 'VM+ HNI Almaz',
    routeCode: 'Bc3D-03',
    shipToCode: '2016',
    soldToCode: '2011',
  },
];
